import type {Metadata} from "next";
import "./globals.css";
import {clsx} from "clsx";
import {GeistSans} from 'geist/font/sans';
import {Toaster} from "sonner";
import Link from "next/link";
import {Profile} from "@/components/auth/profile";
import {LogoutButton} from "@/components/auth/logout-button";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode;
}) {
  return (
      <html lang="en" className="h-full">
      <body className={clsx(GeistSans.className, "flex flex-col w-full h-full")}>
      <header className="min-h-20 w-full flex gap-4 bg-red-400">
        <Link href={"/"}>Main</Link>
        <Link href={"/auth/callback"}>Callback</Link>
        <Link href={"/auth"}>Auth</Link>
        <Link href={"/protected"}>Protected</Link>
        {/*<Profile/>*/}
        <LogoutButton/>

      </header>
      <main className="w-full h-full">
        {children}
      </main>
      <Toaster/>
      </body>
      </html>
  );
}
