import type { Metadata } from "next";
import "./globals.css";
import { clsx } from "clsx";
import { GeistSans } from 'geist/font/sans';
import {Toaster} from "sonner";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode;
}) {
  return (
      <html lang="en" className="h-full">
      <body className={clsx(GeistSans.className, "flex flex-col w-full h-full")}>
      <main className="w-full h-full">
        {children}
      </main>
      <Toaster/>
      </body>
      </html>
  );
}
