services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - .env  # Load environment variables from .env file
    volumes:
      - .:/usr/src/app
    command: npm run start:prod
